### ISSUE TITLE
オーナーが違うファイルロック用のファイルが存在する場合にファイルロックできない

### ISSUE THREAD

**Issue by miyo** [e-trees/e7awg_sw#11]
違うユーザがオーナーになっているファイルロック用のファイルが存在する場合

```
Traceback (most recent call last):
  File "/home/miyo/e7awg_sw/examples/send_recv/send_recv.py", line 204, in <module>
    main(awgs, capture_modules, args.labrad, args.server_ipaddr, args.num_wait_words, save_dir=args.save_dir, timeout=args.timeout, use_sequencer=args.use_sequencer)
  File "/home/miyo/e7awg_sw/examples/send_recv/send_recv.py", line 148, in main
    with (create_awg_ctrl(use_labrad, server_ip_addr) as awg_ctrl,
  File "/home/miyo/e7awg_sw/examples/send_recv/send_recv.py", line 137, in create_awg_ctrl
    return AwgCtrl(IP_ADDR)
  File "/home/miyo/e7awg_sw/e7awgsw/awgctrl.py", line 347, in __init__
    self.__flock = ReentrantFileLock(filepath)
  File "/home/miyo/e7awg_sw/e7awgsw/lock.py", line 14, in __init__
    self.__lock_fp = self.__get_fp(filepath)
  File "/home/miyo/e7awg_sw/e7awgsw/lock.py", line 31, in __get_fp
    raise TimeoutError('[ReentrantFileLock]  open file timeout')
TimeoutError: [ReentrantFileLock]  open file timeout
```

のようになって，ファイルロックが取得できずタイムアウトになる．
該当のファイルロック用ファイルを削除すると意図した動作をする．

**Comment by miyo** [comment]
/tmp にスティッキービットが立っているのが原因．
暫定的に /tmp以外を使うことにする，か？

**Comment by miyo** [comment]
ロック開放時にロックファイルを消すのがいい気がする．

**Comment by miyo** [comment]
ロック開放時にファイルを消すというのは例外的に終了した場合に対応できないので，駄目．
というわけで `/tmp` の下にスティッキービットを立てない `777` なディレクトリを作って，そこにロックファイルをおくことにした．

**Comment by miyo** [comment]
運用上問題なさそうなのでチケットをクローズ
